export const home = "home"
export const cave = "The-Cave"
export const noodles = "n00dles"
export const foodnstuff = "foodnstuff"
export const brutessh = "BruteSSH.exe"
export const ftpcrack = "FTPCrack.exe"
export const relaysmtp = "RelaySMTP.exe"
export const httpworm = "HTTPWorm.exe"
export const sqlinject = "SQLInject.exe"
export const nuke = "NUKE.exe"
export const defaultServerFortifyAmount = 0.002 // Mined from code
export const defaultServerWeakenAmount = 0.05 // Mined from code
export const homeReservedRam = 256
export const thisScript = "timeburn.js"
export const baseRamCost = 1.6 // Mined from code
